version: '3'

services:
  frontend:
    container_name: frontend
    build: .
    command: |
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --workers 3 --bind 0.0.0.0:8001 book_management.wsgi:application
      "
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - shared-network

  consumer:
    container_name: frontend-consumer
    build: .
    command: bash -c "python manage.py consumer"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - shared-network

 
networks:
  shared-network:
    external: true
