version: '3'

services:
  backend:
    container_name: backend
    build: .
    command: |
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn --workers 3 --bind 0.0.0.0:8002 book_management.wsgi:application
      "
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - shared-network

  consumer:
    container_name: backend-consumer
    build: .
    command: bash -c "python manage.py consumer"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
