name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install Flake8
        run: |
          pip install flake8
      
      - name: List files and folders in the root directory
        run: ls -la
      
      - name: Run Flake8
        run: cd back-end && flake8 .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          cd back-end
          pip install -r requirements.txt
          
      - name: Run database migrations
        run: |
          cd back-end
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: cd back-end && python manage.py test
