name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          pip install flake8
      
      - name: Run Flake8
        run: cd front-end && flake8 .

  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         path: frontend
        
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'
        
  #     - name: Install dependencies
  #       run: |
  #         cd frontend
  #         pip install -r requirements.txt
          
  #     - name: Run database migrations
  #       run: |
  #         cd frontend
  #         python manage.py makemigrations
  #         python manage.py migrate

  #     - name: Run tests
  #       run: cd frontend && python manage.py test
